<template>
  <div>
    <div class="loading" v-show="!isLoaded">
      <svg
        class="spinner"
        xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        viewBox="0 0 100 100"
        preserveAspectRatio="xMidYMid"
      >
        <path
          d="M10 50A40 40 0 0 0 90 50A40 42 0 0 1 10 50"
          fill="#0bc0b7"
          stroke="none"
        >
          <animateTransform
            attributeName="transform"
            type="rotate"
            dur="2s"
            repeatCount="indefinite"
            keyTimes="0;1"
            values="0 50 51;360 50 51"
          />
        </path>
        <!-- [ldio] generated by https://loading.io/ -->
      </svg>
    </div>
    <router-view v-show="isLoaded"></router-view>
  </div>
</template>

<script>
export default {
  name: "App",

  data() {
    return {
      isLoaded: false,
    };
  },

  mounted() {
    window.addEventListener("load", () => {
      console.log("loaded");
      this.isLoaded = true;
    });
  },
};
</script>

<style scoped>
@import "@/assets/css/loading.css";
@import "@/assets/css/animations.css";
@import "@/assets/css/global.css";
</style>
