<template>
  <router-view></router-view>
  <div v-if="!isLoaded" class="loading">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      style="
        background: transparent;
        display: block;
        z-index: 201;
        shape-rendering: auto;
      "
      width="50%"
      height="50%"
      viewBox="0 0 100 100"
      preserveAspectRatio="xMidYMid"
    >
      <path
        d="M10 50A40 40 0 0 0 90 50A40 42 0 0 1 10 50"
        fill="#0bc0b7"
        stroke="none"
      >
        <animateTransform
          attributeName="transform"
          type="rotate"
          dur="2s"
          repeatCount="indefinite"
          keyTimes="0;1"
          values="0 50 51;360 50 51"
        />
      </path>
      <!-- [ldio] generated by https://loading.io/ -->
    </svg>
  </div>
</template>

<script>
export default {
  name: "App",

  data() {
    return {
      isLoaded: false,
    };
  },

  created() {
    document.addEventListener("readystatechange", () => {
      if (document.readyState == "complete") this.isLoaded = true;
    });
  },
};
</script>

<style scoped>
@import "@/assets/css/animations.css";
@import "@/assets/css/global.css";

.loading {
  width: 100vw;
  height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: space-evenly;
  align-items: center;
}
</style>
